const environment={
  "schema_version": 1,
  "provider": "OKX",
  "environment": "DEMO_ONLY",
  "operational_identity": "OKX_DEMO_2026_09_03",
  "rest_base_url": "https://openapi.okx.com",
  "public_ws_url": "wss://wspap.okx.com:8443/ws/v5/public",
  "private_ws_url": "wss://wspap.okx.com:8443/ws/v5/private",
  "demo_header": {
    "x-simulated-trading": "1"
  },
  "allowed_instrument_types": [
    "SPOT"
  ],
  "quote_ccy": "USDT",
  "automatic_execution": true,
  "validation_order_requires_explicit_env": "OKX_DEMO_TEST_ORDER_ENABLED=true",
  "live_urls_forbidden": [
    "https://www.okx.com",
    "wss://ws.okx.com:8443/ws/v5/private",
    "wss://ws.okx.com:8443/ws/v5/public"
  ],
  "notes": "Novo contexto operacional. A seleção e a pesquisa devem tratar evidência Deriv/R_100 como histórica, não transferível.",
  "validation_order_enabled": false,
  "validation_order_kind": "ONE_TIME_MINIMUM_SPOT_DEMO_OPERATIONAL_VALIDATION",
  "validation_order_note": "A validação pontual foi concluída; qualquer estratégia, mercado e política de capital devem vir de um Active Mandate materializado no GitHub."
};

const CORS={"Access-Control-Allow-Origin":"https://uparchive.github.io","Access-Control-Allow-Methods":"GET","Cache-Control":"no-store"};
const MAX_STALE_MS=120000,ORDER_TTL_MS=15000,MAX_EVENTS=40,PLAN_CACHE_MS=900000,PLAN_REFRESH_MS=60000;
const PLAN_URL="https://uparchive.github.io/kell-quant-lab/runtime/okx/active_execution_plan.json";
function json(value,status=200){return Response.json(value,{status,headers:CORS})}
function now(){return new Date().toISOString()}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).filter(k=>k!=="plan_hash").sort().map(k=>[k,canonical(v[k])]));return v}
async function digest(v){const bytes=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(canonical(v)))));return [...bytes].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function loadPlan(r){const cached=r.execution_plan,age=cached?.verified_at?Date.now()-Date.parse(cached.verified_at):Infinity;if(cached&&age<PLAN_REFRESH_MS)return cached.plan;try{const res=await fetch(PLAN_URL+"?v="+Date.now(),{headers:{"Cache-Control":"no-store"}});if(!res.ok)throw new Error("MANDATE_FETCH_FAILURE: HTTP "+res.status);const plan=await res.json(),p=plan.strategy?.parameters,x=plan.strategy?.exit,c=plan.capital_policy;if(plan.environment!=="DEMO_ONLY"||plan.provider!=="OKX"||plan.state!=="ACTIVE"||plan.strategy?.engine!=="SUPPORT_RESISTANCE_V1"||!plan.market_selection?.active_instrument||!Number.isFinite(Number(p?.min_touches))||Number(p.min_touches)<2||!Number.isFinite(Number(x?.min_reward_risk))||Number(x.min_reward_risk)<1||!Number.isFinite(Number(c?.risk_per_trade_fraction))||Number(c.risk_per_trade_fraction)<=0||!Number.isFinite(Number(c?.max_position_fraction))||Number(c.max_position_fraction)<=0||Number(c.max_open_positions)!==1)throw new Error("MANDATE_INVALID: policy or authorization");if(await digest(plan)!==plan.plan_hash)throw new Error("MANDATE_INVALID: hash mismatch");r.execution_plan={plan,verified_at:now(),source:PLAN_URL};return plan}catch(e){if(cached&&age<PLAN_CACHE_MS)return cached.plan;throw e}}
function event(r,label,detail,market=r.telemetry.active_market){r.telemetry.recent_events.unshift({timestamp:now(),market,label,detail});r.telemetry.recent_events=r.telemetry.recent_events.slice(0,MAX_EVENTS)}
function baseRuntime(){return {provider:"OKX",provider_environment:"DEMO",environment:"DEMO_ONLY",experimental_context_id:environment.operational_identity,status:"INITIALIZING",balance:null,equity:null,pnl_today:0,drawdown:0,last_cycle_at:null,last_success_at:null,last_trade_at:null,selected_markets:[],issues:[],position:null,telemetry:{active_market:null,tick:null,tick_timestamp:null,tick_stale:true,support_levels:[],resistance_levels:[],signal_state:"NO_VALID_SIGNAL",regime:"UNCLASSIFIED",recent_events:[],connection:{rest:"UNKNOWN",private_ws:"UNKNOWN",public_market_data:"UNKNOWN",auth:"UNKNOWN"},metrics:{reconnects:0,rate_limits:0,rest_requests:0,ws_messages:0,technical_degraded_ms:0}},recent_trades:[],idempotency:{},validation:{instruments:false,market_data:false,account:false,private_ws:false,order:false}}}
function runtime(raw){const migrated=raw?.provider!=="OKX";const r={...baseRuntime(),...(raw||{})};if(migrated){r.issues=[];r.recent_trades=[];r.idempotency={};r.position=null;r.telemetry=baseRuntime().telemetry}r.issues=Array.isArray(r.issues)?r.issues:[];r.selected_markets=Array.isArray(r.selected_markets)?r.selected_markets:[];r.recent_trades=Array.isArray(r.recent_trades)?r.recent_trades:[];r.idempotency=r.idempotency&&typeof r.idempotency==="object"?r.idempotency:{};r.position=r.position&&typeof r.position==="object"?r.position:null;r.telemetry={...baseRuntime().telemetry,...(r.telemetry||{})};r.telemetry.connection={...baseRuntime().telemetry.connection,...(r.telemetry.connection||{})};r.telemetry.metrics={...baseRuntime().telemetry.metrics,...(r.telemetry.metrics||{})};r.telemetry.support_levels=Array.isArray(r.telemetry.support_levels)?r.telemetry.support_levels:[];r.telemetry.resistance_levels=Array.isArray(r.telemetry.resistance_levels)?r.telemetry.resistance_levels:[];r.telemetry.recent_events=Array.isArray(r.telemetry.recent_events)?r.telemetry.recent_events:[];return r}
function safe(r){const supportLevels=r.telemetry.support_levels.filter(Number.isFinite),resistanceLevels=r.telemetry.resistance_levels.filter(Number.isFinite),support=supportLevels[0]??null,resistance=resistanceLevels[0]??null,plan=r.execution_plan?.plan;return {...r,timestamp:now(),open_positions:r.position?1:0,open_contract:r.position,platform_state:r.status==="TECHNICAL_FAIL_CLOSED"?"PLATFORM_UNDER_INVESTIGATION":"PLATFORM_OK",public_ws_url:environment.public_ws_url,operational_strategy:plan?.strategy?.engine||"NO_VALID_MANDATE",strategy_version:plan?.strategy?.version||"NO_VALID_MANDATE",strategy_status:plan?.state||"NO_VALID_MANDATE",capital_policy_version:plan?.capital_policy?.version||"NO_VALID_MANDATE",active_mandate:plan?{plan_id:plan.plan_id,plan_hash:plan.plan_hash,verified_at:r.execution_plan.verified_at}:null,active_market:r.telemetry.active_market,signal_state:r.telemetry.signal_state,regime:r.telemetry.regime,tick:r.telemetry.tick,tick_timestamp:r.telemetry.tick_timestamp,tick_stale:r.telemetry.tick_stale,support,resistance,support_target:support,resistance_target:resistance,support_levels:supportLevels,resistance_levels:resistanceLevels,trade_plan:{support,resistance,entry_zone:support,exit_target:resistance,stop_price:r.position?.stop_price??null,take_profit_price:r.position?.target_price??null,signal:r.telemetry.signal_state,regime:r.telemetry.regime},recent_events:r.telemetry.recent_events.slice(0,30)}}
function fail(r,code,message){r.status="TECHNICAL_FAIL_CLOSED";r.issues.push({at:now(),code,message:String(message).replace(/(OK-ACCESS-(?:KEY|SIGN|PASSPHRASE)[:=]\s*)\S+/gi,"$1[REDACTED]").slice(0,240)});r.issues=r.issues.slice(-50);event(r,"FALHA TÉCNICA",code);return r}
function assertDemo(env){if(environment.environment!=="DEMO_ONLY"||environment.demo_header["x-simulated-trading"]!=="1"||environment.automatic_execution!==true)throw new Error("DEMO_GUARD_REJECTED: immutable provider configuration");if(!/^https:\/\/openapi\.okx\.com$/.test(environment.rest_base_url)||environment.private_ws_url!=="wss://wspap.okx.com:8443/ws/v5/private"||environment.public_ws_url!=="wss://wspap.okx.com:8443/ws/v5/public")throw new Error("DEMO_GUARD_REJECTED: non-demo endpoint");if(!env.OKX_API_KEY||!env.OKX_SECRET_KEY||!env.OKX_PASSPHRASE)throw new Error("CREDENTIAL_MISMATCH: missing OKX Demo credential")}
function b64(bytes){let s="";for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s)}
async function hmac(secret,prehash){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(prehash)))}
async function privateHeaders(env,method,path,body=""){assertDemo(env);const timestamp=now(),sign=await hmac(env.OKX_SECRET_KEY,timestamp+method.toUpperCase()+path+body);return {"Content-Type":"application/json","OK-ACCESS-KEY":env.OKX_API_KEY,"OK-ACCESS-SIGN":sign,"OK-ACCESS-TIMESTAMP":timestamp,"OK-ACCESS-PASSPHRASE":env.OKX_PASSPHRASE,"x-simulated-trading":"1"}}
async function okx(env,r,method,path,payload){const body=payload?JSON.stringify(payload):"";const headers=await privateHeaders(env,method,path,body);let res;try{res=await fetch(environment.rest_base_url+path,{method,headers,body:body||undefined})}catch(e){throw new Error("REST_NETWORK_FAILURE: "+(e?.message||"fetch failed"))}r.telemetry.metrics.rest_requests++;if(res.status===429){r.telemetry.metrics.rate_limits++;throw new Error("RATE_LIMIT: HTTP 429")}const data=await res.json().catch(()=>({}));if(!res.ok||data.code!=="0")throw new Error("OKX_API_ERROR: "+(data.code||res.status)+" "+(data.msg||"request rejected"));return data.data||[]}
async function publicGet(r,path){let res;try{res=await fetch(environment.rest_base_url+path,{headers:{"x-simulated-trading":"1"}})}catch(e){throw new Error("MARKET_DATA_NETWORK_FAILURE: "+(e?.message||"fetch failed"))}r.telemetry.metrics.rest_requests++;const data=await res.json().catch(()=>({}));if(!res.ok||data.code!=="0")throw new Error("MARKET_DATA_FAILURE: "+(data.code||res.status));return data.data||[]}
function candidate(instruments,plan){const m=plan.market_selection;return instruments.find(x=>x.instId===m.active_instrument&&x.instType===m.instrument_type&&x.quoteCcy===m.quote_ccy&&x.state==="live"&&Number(x.minSz)>0&&Number(x.tickSz)>0&&Number(x.lotSz)>0)||null}
async function validatePrivateWs(env,r){assertDemo(env);const ts=Math.floor(Date.now()/1000).toString(),sign=await hmac(env.OKX_SECRET_KEY,ts+"GET"+"/users/self/verify");let response;try{response=await fetch(environment.private_ws_url.replace(/^wss:/,"https:"),{headers:{Upgrade:"websocket","x-simulated-trading":"1"}})}catch(e){throw new Error("PRIVATE_WS_CONNECT_FAILURE: "+(e?.message||"fetch failed"))}if(!response.webSocket)throw new Error("PRIVATE_WS_CONNECT_FAILURE: HTTP "+response.status);const ws=response.webSocket;ws.accept();try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("PRIVATE_WS_LOGIN_TIMEOUT")),10000);const listener=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.event==="login"){clearTimeout(timer);ws.removeEventListener("message",listener);m.code==="0"?resolve(m):reject(new Error("PRIVATE_WS_LOGIN_REJECTED: "+(m.code||"unknown")))}};ws.addEventListener("message",listener);ws.send(JSON.stringify({op:"login",args:[{apiKey:env.OKX_API_KEY,passphrase:env.OKX_PASSPHRASE,timestamp:ts,sign}]}))});r.validation.private_ws=true;r.telemetry.connection.private_ws="AUTHENTICATED";r.telemetry.connection.auth="AUTHENTICATED"}finally{try{ws.close(1000,"cycle complete")}catch(_){}}}
function roundDown(value,step){const n=Number(value),s=Number(step);if(!Number.isFinite(n)||!Number.isFinite(s)||s<=0)return null;const decimals=(String(step).split(".")[1]||"").length;return (Math.floor((n+1e-12)/s)*s).toFixed(decimals)}
function candles(raw){return raw.map(x=>({ts:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),confirmed:String(x[8]??"1")==="1"})).filter(x=>x.confirmed&&[x.open,x.high,x.low,x.close].every(Number.isFinite)).sort((a,b)=>a.ts-b.ts)}
function analysis(c,strategy){const p=strategy.parameters,e=strategy.entry,x=strategy.exit,wid=Number(p.zone_width_atr),pivot=Number(p.pivot_window),minTouches=Number(p.min_touches);if(c.length<40)return {signal:"WAIT",regime:"UNKNOWN",support:[],resistance:[],reason:"insufficient candles"};const dif=c.slice(-21).slice(1).map((v,i)=>Math.max(v.high-c[i+c.length-21].low,Math.abs(v.high-c[i+c.length-21].close),Math.abs(v.low-c[i+c.length-21].close))),atr=dif.reduce((a,b)=>a+b,0)/dif.length;if(!Number.isFinite(atr)||atr<=0)return {signal:"WAIT",regime:"UNKNOWN",support:[],resistance:[],reason:"invalid ATR"};const piv=[];for(let i=pivot;i<c.length-pivot;i++){const w=c.slice(i-pivot,i+pivot+1);if(c[i].low===Math.min(...w.map(v=>v.low)))piv.push({kind:"SUPPORT",value:c[i].low,at:c[i].ts});if(c[i].high===Math.max(...w.map(v=>v.high)))piv.push({kind:"RESISTANCE",value:c[i].high,at:c[i].ts})}const last=c.at(-1),prev=c.at(-2),width=atr*wid,levels=kind=>piv.filter(v=>v.kind===kind).map(v=>({...v,touches:piv.filter(q=>q.kind===kind&&Math.abs(q.value-v.value)<=width).length})).filter(v=>v.touches>=minTouches);const supports=levels("SUPPORT").filter(v=>v.value<=last.close+width).sort((a,b)=>b.value-a.value).slice(0,3),resistance=levels("RESISTANCE").filter(v=>v.value>=last.close+width).sort((a,b)=>a.value-b.value).slice(0,3),support=supports[0],res=resistance[0],entryDistance=support?last.close-support.value:Infinity,stop=support?support.value-atr*Number(x.stop_atr_buffer):null,target=res?res.value:null,stopPct=stop?(last.close-stop)/last.close:Infinity,targetPct=target?(target-last.close)/last.close:-Infinity,rejection=!!support&&prev.low<=support.value+width&&last.low<=support.value+width&&(!e.require_bullish_candle||last.close>last.open)&&(!e.require_close_above_previous||last.close>prev.close),rr=targetPct/stopPct,minGross=(Number(x.estimated_round_trip_fee_bps)+Number(x.min_net_target_bps))/10000,valid=rejection&&entryDistance<=atr*Number(p.max_entry_distance_atr)&&stopPct>0&&stopPct<=Number(x.max_stop_loss_pct)&&targetPct>=minGross&&rr>=Number(x.min_reward_risk);const trend=Math.abs(last.close-c.at(-20).close)/(atr*20);let reason="no validated entry";if(rejection&&!valid)reason="entry rejected: reward/risk, costs, stop or distance";else if(valid)reason="validated support rejection";return {signal:valid?"BUY":"WAIT",regime:trend<.35?"RANGING":trend>.8?"TRENDING":"MIXED",support:supports,resistance,activeSupport:support||null,activeResistance:res||null,atr,trade:valid?{stop_price:stop,target_price:target,stop_pct:stopPct,target_pct:targetPct,reward_risk:rr,expected_net_target_pct:targetPct-Number(x.estimated_round_trip_fee_bps)/10000}:null,reason}}
async function append(store,event){const seq=((await store.storage.get("ledger:seq"))||0)+1;await store.storage.put("ledger:seq",seq);await store.storage.put("ledger:"+String(seq).padStart(12,"0"),{seq,...event})}
function idKey(inst,side){return inst+"|"+side+"|"+Math.floor(Date.now()/60000)}
async function place(env,r,inst,side,sz){const key=idKey(inst.instId,side);if(r.idempotency[key])return null;const clOrdId=("KQL"+Date.now()+side[0]).slice(0,32);r.idempotency[key]="PENDING";const orders=await okx(env,r,"POST","/api/v5/trade/order",{instId:inst.instId,tdMode:"cash",side,ordType:"market",sz,tgtCcy:side==="buy"?"base_ccy":undefined,clOrdId,expTime:String(Date.now()+ORDER_TTL_MS)});const order=orders[0];if(!order?.ordId||order.sCode!=="0")throw new Error("ORDER_REJECTED: "+(order?.sMsg||"missing order id"));r.idempotency[key]=order.ordId;return {ordId:order.ordId,clOrdId}}
async function openPosition(store,env,r,inst,plan,trade){const risk=plan.capital_policy,px=r.telemetry.tick,equity=Number(r.equity),minQuote=Number(inst.minSz)*px,stopPct=Number(trade?.stop_pct),riskBudget=equity*Number(risk.risk_per_trade_fraction),riskSizedNotional=riskBudget/stopPct,maximumNotional=equity*Number(risk.max_position_fraction),requested=Math.min(riskSizedNotional,maximumNotional);if(!Number.isFinite(px)||px<=0)throw new Error("EXECUTION_BLOCKED: invalid market price");if(!Number.isFinite(equity)||equity<=0)throw new Error("EXECUTION_BLOCKED: invalid account equity");if(!Number.isFinite(stopPct)||stopPct<=0||!Number.isFinite(requested)||requested<minQuote)throw new Error("EXECUTION_BLOCKED: invalid risk-sized quantity");const size=roundDown(requested/px,inst.lotSz);if(!(Number(size)>0))throw new Error("EXECUTION_BLOCKED: invalid position size");const order=await place(env,r,inst,"buy",size);if(!order)return;const pos={position_id:"P-"+Date.now(),instrument:inst.instId,base_ccy:inst.baseCcy,qty:Number(size),entry_price:px,notional:Math.round(Number(size)*px*1e8)/1e8,risk_budget:Math.round(riskBudget*1e8)/1e8,opened_at:now(),stop_price:trade.stop_price,target_price:trade.target_price,expected_reward_risk:trade.reward_risk,order_id:order.ordId,strategy_version:plan.strategy.version,mandate_id:plan.plan_id,mandate_hash:plan.plan_hash};r.position=pos;r.last_trade_at=pos.opened_at;await append(store,{event_type:"POSITION_OPENED",timestamp:pos.opened_at,...pos,environment:"DEMO_ONLY"});event(r,"OPERAÇÃO DEMO ABERTA","BUY Spot · "+size+" "+inst.baseCcy+" · risco máx. estimado "+(pos.notional*stopPct).toFixed(2)+" USDT",inst.instId)}
async function closePosition(store,env,r,reason){const pos=r.position;if(!pos)return;const instruments=await publicGet(r,"/api/v5/public/instruments?instType=SPOT&instId="+encodeURIComponent(pos.instrument));const inst=instruments[0];if(!inst)throw new Error("RECONCILIATION_FAILURE: active instrument missing");const size=roundDown(pos.qty,inst.lotSz);if(!(Number(size)>0))throw new Error("RECONCILIATION_FAILURE: sell size invalid");const order=await place(env,r,inst,"sell",size);if(!order)return;const pnl=(r.telemetry.tick-pos.entry_price)*pos.qty;r.pnl_today+=pnl;const settled={event_type:"POSITION_CLOSED",timestamp:now(),...pos,close_price:r.telemetry.tick,pnl,result:pnl>0?"WIN":pnl<0?"LOSS":"FLAT",reason,close_order_id:order.ordId};r.recent_trades.unshift(settled);r.recent_trades=r.recent_trades.slice(0,20);await append(store,settled);event(r,"OPERAÇÃO DEMO ENCERRADA",reason+" · "+(pnl>=0?"+":"")+pnl.toFixed(4)+" USDT",pos.instrument);r.position=null}
async function run(store,env){let r=runtime(await store.storage.get("runtime"));r.last_cycle_at=now();try{assertDemo(env);const plan=await loadPlan(r),all=await publicGet(r,"/api/v5/public/instruments?instType=SPOT"),inst=candidate(all,plan);if(!inst)throw new Error("NO_AUTHORIZED_INSTRUMENT");r.validation.instruments=true;r.selected_markets=[inst.instId];r.telemetry.active_market=inst.instId;const tick=(await publicGet(r,"/api/v5/market/ticker?instId="+encodeURIComponent(inst.instId)))[0];if(!tick?.last)throw new Error("MARKET_DATA_STALE: ticker missing");r.telemetry.tick=Number(tick.last);r.telemetry.tick_timestamp=new Date(Number(tick.ts)).toISOString();r.telemetry.tick_stale=Date.now()-Number(tick.ts)>MAX_STALE_MS;r.telemetry.connection.public_market_data=r.telemetry.tick_stale?"STALE":"CONNECTED";r.validation.market_data=true;if(r.telemetry.tick_stale)throw new Error("MARKET_DATA_STALE");const account=await okx(env,r,"GET","/api/v5/account/balance");r.balance=Number(account[0]?.totalEq)||null;r.equity=r.balance;r.validation.account=true;r.telemetry.connection.rest="AUTHENTICATED";await validatePrivateWs(env,r);const a=analysis(candles(await publicGet(r,"/api/v5/market/history-candles?instId="+encodeURIComponent(inst.instId)+"&bar="+encodeURIComponent(plan.strategy.parameters.timeframe)+"&limit="+encodeURIComponent(plan.strategy.parameters.lookback_candles))),plan.strategy);r.telemetry.support_levels=a.support.map(x=>x.value);r.telemetry.resistance_levels=a.resistance.map(x=>x.value);r.telemetry.signal_state=a.signal;r.telemetry.regime=a.regime;r.strategy={id:plan.strategy.strategy_id,version:plan.strategy.version,engine:plan.strategy.engine};r.instrument_context={instId:inst.instId,instType:inst.instType,baseCcy:inst.baseCcy,quoteCcy:inst.quoteCcy,minSz:inst.minSz,lotSz:inst.lotSz,tickSz:inst.tickSz,analysis_reason:a.reason,proposed_trade:a.trade};if(r.position){if(r.telemetry.tick<=r.position.stop_price)await closePosition(store,env,r,"STOP_LOSS");else if(r.telemetry.tick>=r.position.target_price)await closePosition(store,env,r,"TAKE_PROFIT");else if(a.activeResistance&&r.telemetry.tick>=a.activeResistance.value)await closePosition(store,env,r,"RESISTANCE");r.status=r.position?"MONITORING":"WAITING_SIGNAL"}else if(a.signal==="BUY"&&a.trade){await openPosition(store,env,r,inst,plan,a.trade);r.status=r.position?"MONITORING":"WAITING_SIGNAL"}else r.status="WAITING_SIGNAL";r.last_success_at=now();event(r,"CICLO MANDATO OKX","Sinal: "+a.signal+" · "+a.reason,inst.instId)}catch(e){fail(r,String(e.message||e).split(":")[0],e.message||e)}await store.storage.put("runtime",r);return safe(r)}
export class ExecutorState{constructor(state,env){this.state=state;this.env=env}async fetch(req){const p=new URL(req.url).pathname;if(p==="/run")return json(await this.state.blockConcurrencyWhile(()=>run(this.state,this.env)));if(p==="/state"||p==="/live")return json(safe(runtime(await this.state.storage.get("runtime"))));if(p==="/ledger")return json({events:(await this.state.storage.list({prefix:"ledger:"})).values()});return new Response("Not found",{status:404})}}
export default {async fetch(req,env){const p=new URL(req.url).pathname,stub=env.EXECUTOR_STATE.get(env.EXECUTOR_STATE.idFromName("primary"));if(p==="/health")return json({ok:true,provider:"OKX",environment:"DEMO_ONLY",live_money:false,mandate_source:PLAN_URL});if(p==="/executor-state"){const response=await stub.fetch("https://internal/state");return new Response(response.body,{headers:CORS})}if(p==="/run")return stub.fetch("https://internal/run");return json({service:"Kell Quant Lab",provider:"OKX",environment:"DEMO_ONLY",mandate_source:PLAN_URL})},async scheduled(_c,env,ctx){const stub=env.EXECUTOR_STATE.get(env.EXECUTOR_STATE.idFromName("primary"));ctx.waitUntil(stub.fetch("https://internal/run"))}};
