import mandate from "../config/v4/active_mandate.json";
import strategies from "../config/v4/strategy_registry.json";
import policies from "../config/v4/capital_policy_registry.json";
import selection from "../config/v4/market_selection.json";
import governance from "../config/v4/platform_governance.json";

const API="https://api.derivws.com",PUBLIC="wss://api.derivws.com/trading/v1/options/ws/public",DEMO_PATH="/trading/v1/options/ws/demo";
const RUN_STATES=new Set(["WAITING_SIGNAL","EXECUTING","MONITORING","SETTLING"]);
const OFF_STATES=new Set(governance.extraordinary_off_states);
let latestScan=[];
let lastScanAt=0;
const SCAN_INTERVAL_MS=5*60_000;
const DEMO_SESSION_INTERVAL_MS=SCAN_INTERVAL_MS;
let scanBlockedUntil=0;
const READ_ONLY_CORS={"Access-Control-Allow-Origin":"https://uparchive.github.io","Access-Control-Allow-Methods":"GET","Cache-Control":"no-store"};
function readOnlyJson(value){return Response.json(value,{headers:READ_ONLY_CORS})}
async function withCors(response){const headers=new Headers(response.headers);for(const [key,value] of Object.entries(READ_ONLY_CORS))headers.set(key,value);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}

export class ExecutorState{
  constructor(state,env){this.state=state;this.env=env}
  async fetch(req){const p=new URL(req.url).pathname;if(p==="/run")return this.state.blockConcurrencyWhile(async()=>Response.json(await run(this.state,this.env)));if(p==="/state"||p==="/live")return Response.json(safe((await this.state.storage.get("runtime"))||fresh()));if(p==="/ledger")return Response.json({events:(await this.state.storage.list({prefix:"ledger:"})).values()});return new Response("Not found",{status:404})}
}
export default{
  async fetch(req,env){const p=new URL(req.url).pathname;if(p==="/health")return readOnlyJson({ok:true,version:"4.0.0",environment:"DEMO_ONLY",mode:"continuous_scheduled_executor",mandate:mandate.mandate_id,strategy:mandate.strategy_version,champion:strategies.champion,platform_state:governance.platform_state});const stub=env.EXECUTOR_STATE.get(env.EXECUTOR_STATE.idFromName("primary"));if(p==="/executor-state"){const response=await stub.fetch("https://internal/state");return withCors(response)}if(p==="/run")return stub.fetch("https://internal/run");return readOnlyJson({service:"Kell Quant Lab V4",status:"online",environment:"DEMO_ONLY"})},
  async scheduled(_c,env,ctx){const stub=env.EXECUTOR_STATE.get(env.EXECUTOR_STATE.idFromName("primary"));ctx.waitUntil(stub.fetch("https://internal/run"))}
};
function fresh(){return{status:"WAITING_SIGNAL",balance:null,equity:null,peak_equity:null,drawdown:0,pnl_today:0,pnl_local_date:null,last_cycle_at:null,last_trade_at:null,trades_today:0,local_date:null,next_demo_session_at:null,tracked:[],idempotency:{},issues:[],selected_markets:mandate.authorized_markets,scan_cache:[],scan_blocked_until:0,telemetry:{active_market:null,tick:null,tick_timestamp:null,tick_stale:false,support_levels:[],resistance_levels:[],signal_state:"WAIT",recent_events:[]}}}
function normalizeRuntime(raw){
  const base=fresh();
  const r=raw&&typeof raw==="object"?{...base,...raw}:base;
  r.tracked=Array.isArray(r.tracked)?r.tracked:[];
  r.idempotency=r.idempotency&&typeof r.idempotency==="object"&&!Array.isArray(r.idempotency)?r.idempotency:{};
  r.issues=Array.isArray(r.issues)?r.issues:[];
  r.scan_cache=Array.isArray(r.scan_cache)?r.scan_cache:[];
  r.scan_blocked_until=Number.isFinite(Number(r.scan_blocked_until))?Number(r.scan_blocked_until):0;
  r.selected_markets=Array.isArray(r.selected_markets)&&r.selected_markets.length?r.selected_markets:mandate.authorized_markets;
  r.telemetry=r.telemetry&&typeof r.telemetry==="object"&&!Array.isArray(r.telemetry)?r.telemetry:base.telemetry;
  r.telemetry.support_levels=Array.isArray(r.telemetry.support_levels)?r.telemetry.support_levels:[];
  r.telemetry.resistance_levels=Array.isArray(r.telemetry.resistance_levels)?r.telemetry.resistance_levels:[];
  r.telemetry.recent_events=Array.isArray(r.telemetry.recent_events)?r.telemetry.recent_events:[];
  if(!r.scan_cache.length&&r.telemetry.active_market)r.scan_cache=[{market:r.telemetry.active_market,tick:r.telemetry.tick??null,tick_timestamp:r.telemetry.tick_timestamp??null,support_levels:r.telemetry.support_levels,resistance_levels:r.telemetry.resistance_levels,signal:"WAIT",regime:r.telemetry.regime||"UNKNOWN",score:0,zone:null}];
  r.trades_today=Number.isFinite(Number(r.trades_today))?Number(r.trades_today):0;
  r.drawdown=Number.isFinite(Number(r.drawdown))?Number(r.drawdown):0;
  if(Number.isFinite(Number(r.equity))){r.peak_equity=Math.max(Number(r.peak_equity)||Number(r.equity),Number(r.equity));r.drawdown=Math.max(0,((r.peak_equity-Number(r.equity))/r.peak_equity)*100)}
  return r;
}
function safe(r){const lead=latestScan[0]||r.scan_cache?.[0]||{},tickTimestamp=r.telemetry?.tick_timestamp??lead.tick_timestamp??null;return{environment:"DEMO_ONLY",timestamp:new Date().toISOString(),status:r.status,balance:r.balance,equity:r.equity,pnl_today:r.pnl_today||0,drawdown:r.drawdown,last_cycle_at:r.last_cycle_at,last_trade_at:r.last_trade_at,trades_today:r.trades_today,open_positions:r.tracked?.length||0,open_contract:r.tracked?.[0]||null,selected_markets:r.selected_markets||[],mandate_id:mandate.mandate_id,strategy_id:mandate.strategy_id,strategy_version:mandate.strategy_version,capital_policy_id:mandate.capital_policy_id,capital_policy_version:mandate.capital_policy_version,platform_state:governance.platform_state,active_market:r.telemetry?.active_market||lead.market||null,tick:r.telemetry?.tick??lead.tick??null,tick_timestamp:normalizeTimestamp(tickTimestamp),tick_stale:r.telemetry?.tick_stale===true||lead.stale===true,support_levels:r.telemetry?.support_levels?.length?r.telemetry.support_levels:(lead.support_levels||[]),resistance_levels:r.telemetry?.resistance_levels?.length?r.telemetry.resistance_levels:(lead.resistance_levels||[]),signal_state:r.telemetry?.signal_state||lead.signal||"WAIT",regime:r.telemetry?.regime||lead.regime||"UNKNOWN",recent_events:r.telemetry?.recent_events||[],recent_trades:r.recent_trades||[],issues:(r.issues||[]).slice(-5)}}
function normalizeTimestamp(value){if(!value)return null;if(typeof value==="number"||/^\d+(\.\d+)?$/.test(String(value))){const numeric=Number(value);return Number.isFinite(numeric)?new Date(numeric<1e12?numeric*1000:numeric).toISOString():null}const date=new Date(value);return Number.isNaN(date.getTime())?null:date.toISOString()}
function validate(){if(governance.environment!=="DEMO_ONLY"||governance.real_money_allowed!==false||governance.real_endpoint_paths.length!==0)throw new Error("TECHNICAL_FAIL_CLOSED: DEMO_ONLY barrier");if(governance.platform_state==="PLATFORM_REJECTED")throw new Error("PLATFORM_REJECTED");if(mandate.environment!=="DEMO_ONLY"||mandate.state!=="ACTIVE")throw new Error("TECHNICAL_FAIL_CLOSED: invalid mandate");if(!mandate.authorized_markets.length||mandate.authorized_markets.length>3)throw new Error("STATE_CORRUPTED: invalid market count");const incumbent=strategies.champion||strategies.strategies.find(x=>x.kind==="BASELINE"&&x.status==="OPERATIONAL_INCUMBENT")?.version;if(!incumbent||incumbent!==mandate.strategy_version)throw new Error("STATE_CORRUPTED: mandate/incumbent mismatch")}
async function run(store,env){let r=normalizeRuntime(await store.storage.get("runtime"));const recovering=r.status==="TECHNICAL_FAIL_CLOSED";r.last_cycle_at=new Date().toISOString();try{validate();const today=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo"}).format(new Date());if(r.local_date!==today){r.local_date=today;r.trades_today=0}if(r.pnl_local_date!==today){r.pnl_local_date=today;r.pnl_today=0}const nextSession=Date.parse(r.next_demo_session_at||"");if(!recovering&&!r.tracked.length&&Number.isFinite(nextSession)&&Date.now()<nextSession){await store.storage.put("runtime",r);return safe(r)}const ws=await demoSocket(env,r);try{const account=await call(ws,{balance:1,subscribe:0,req_id:10},"balance");r.balance=Number(account.balance?.balance);r.equity=r.balance;r.peak_equity=Math.max(Number(r.peak_equity)||r.equity,r.equity);r.drawdown=Math.max(0,((r.peak_equity-r.equity)/r.peak_equity)*100);r.status="SETTLING";await reconcile(ws,store,r);r.status=r.tracked.length?"MONITORING":"WAITING_SIGNAL";const ranked=await scan(mandate.authorized_markets,r.scan_cache,r);if(!ranked.every(x=>x.stale===true))r.scan_cache=ranked;r.selected_markets=ranked.slice(0,3).map(x=>x.market);materializeTelemetry(r,ranked);if(!recovering)for(const item of ranked){if(r.tracked.length)break;const key=await evaluateAndTrade(ws,store,r,item,env);if(key)break}r.next_demo_session_at=r.tracked.length?null:new Date(Date.now()+DEMO_SESSION_INTERVAL_MS).toISOString()}finally{try{ws.close(1000,"cycle complete")}catch(_){}}}catch(e){const code=String(e.message||e).split(":")[0];r.status=OFF_STATES.has(code)?code:"TECHNICAL_FAIL_CLOSED";r.issues.push({at:new Date().toISOString(),code,message:String(e.message||e).slice(0,240)});r.issues=r.issues.slice(-50)}await store.storage.put("runtime",r);return safe(r)}
function materializeTelemetry(r,ranked){const lead=ranked[0];if(!lead)return;r.telemetry.active_market=lead.market||null;r.telemetry.tick=lead.tick??null;r.telemetry.tick_timestamp=normalizeTimestamp(lead.tick_timestamp);r.telemetry.tick_stale=lead.stale===true;r.telemetry.support_levels=Array.isArray(lead.support_levels)?lead.support_levels:[];r.telemetry.resistance_levels=Array.isArray(lead.resistance_levels)?lead.resistance_levels:[];r.telemetry.signal_state=lead.signal||"WAIT";r.telemetry.regime=lead.regime||"UNKNOWN"}
function assertExecutionGate(ws,r){validate();if(r.status!=="WAITING_SIGNAL"&&r.status!=="EXECUTING")throw new Error(`TECHNICAL_FAIL_CLOSED: execution gate status=${r.status}`);if(r.tracked.length)throw new Error("TECHNICAL_FAIL_CLOSED: execution gate open position");if(ws.readyState!==WebSocket.OPEN)throw new Error("TECHNICAL_FAIL_CLOSED: execution gate socket not open")}
async function evaluateAndTrade(ws,store,r,item){if(item.signal==="WAIT")return null;assertExecutionGate(ws,r);const epoch=Math.floor(Date.now()/60000),key=await sha(`${mandate.mandate_id}|${item.market}|${epoch}|${item.signal}`);if(r.idempotency[key]||await store.storage.get(`idem:${key}`))return null;const policy=policies.policies.find(x=>x.version===mandate.capital_policy_version);const stake=size(r.balance,policy);r.status="EXECUTING";await store.storage.put(`idem:${key}`,{state:"PENDING",at:new Date().toISOString()});r.idempotency[key]="PENDING";assertExecutionGate(ws,r);const proposal=(await call(ws,{proposal:1,amount:stake,basis:"stake",contract_type:item.signal,currency:"USD",duration:mandate.duration.value,duration_unit:mandate.duration.unit,underlying_symbol:item.market,req_id:20},"proposal")).proposal;if(!proposal?.id||proposal.ask_price==null)throw new Error("EXECUTION_FAILURE: incomplete proposal");assertExecutionGate(ws,r);const buy=(await call(ws,{buy:proposal.id,price:Number(proposal.ask_price),req_id:21},"buy")).buy;if(!buy?.contract_id)throw new Error("EXECUTION_FAILURE: buy missing contract id");const event={event_type:"TRADE_OPENED",trade_id:`T-${Date.now()}-${buy.contract_id}`,contract_id:String(buy.contract_id),idempotency_key:key,mandate_id:mandate.mandate_id,strategy_version:mandate.strategy_version,capital_policy_version:mandate.capital_policy_version,market_selection_version:mandate.market_selection_version,market:item.market,regime:item.regime,signal:item.signal,timestamp:new Date().toISOString(),direction:item.signal,contract:item.signal,duration:mandate.duration,stake,balance_before:r.balance,payout:Number(proposal.payout||0),latency:null,provenance:{engine:"BASELINE_SUPPORT_RESISTANCE",zone:item.zone}};await append(store,event);r.tracked.push(event);r.idempotency[key]="ACCEPTED";await store.storage.put(`idem:${key}`,{state:"ACCEPTED",contract_id:event.contract_id,trade_id:event.trade_id});r.trades_today+=1;r.last_trade_at=event.timestamp;r.telemetry.recent_events.unshift({timestamp:event.timestamp,market:item.market,label:"OPERAÇÃO DEMO ABERTA",detail:`${item.signal} · stake $${stake.toFixed(2)}`});r.telemetry.recent_events=r.telemetry.recent_events.slice(0,30);return key}
async function reconcile(ws,store,r){const keep=[];for(const t of r.tracked){const c=(await call(ws,{proposal_open_contract:1,contract_id:t.contract_id,req_id:30},"proposal_open_contract")).proposal_open_contract||{};if(c.is_sold||c.is_expired){const pnl=Number(c.profit||0);const event={...t,event_type:"TRADE_SETTLED",timestamp:new Date().toISOString(),result:pnl>0?"WIN":pnl<0?"LOSS":"FLAT",pnl,balance_after:r.balance,equity:r.equity};await append(store,event);r.pnl_today=Number(r.pnl_today||0)+pnl;r.recent_trades=[event,...(r.recent_trades||[])].slice(0,20);r.telemetry.recent_events.unshift({timestamp:event.timestamp,market:t.market,label:"CONTRATO ENCERRADO",detail:`${event.result} ${pnl>=0?"+":""}$${pnl.toFixed(2)}`});delete r.idempotency[t.idempotency_key]}else keep.push(t)}r.tracked=keep}
async function append(store,event){const seq=((await store.storage.get("ledger:seq"))||0)+1;await store.storage.put("ledger:seq",seq);await store.storage.put(`ledger:${String(seq).padStart(12,"0")}`,{seq,...event})}
function size(balance,policy){if(!Number.isFinite(balance)||balance<=0)throw new Error("TECHNICAL_FAIL_CLOSED: invalid DEMO balance");const p=policy.parameters;const raw=balance*Number(p.equity_fraction),v=Math.max(Number(p.min_stake),Math.min(Number(p.max_stake),raw));return Math.round(v/Number(p.rounding))*Number(p.rounding)}
function staleScan(items){return items.map(x=>({...x,signal:"WAIT",stale:true}))}
async function scan(markets,persistedCache=[],runtime={}){const cached=latestScan.length?latestScan:(Array.isArray(persistedCache)?persistedCache:[]),blockedUntil=Math.max(scanBlockedUntil,Number(runtime.scan_blocked_until)||0);if(cached.length&&(Date.now()<blockedUntil||Date.now()-lastScanAt<SCAN_INTERVAL_MS))return staleScan(cached);const out=[];try{for(const market of markets){const msg=await publicCall({ticks_history:market,count:Math.max(60,mandate.parameters.lookback),end:"latest",style:"ticks",req_id:40});const p=(msg.history?.prices||[]).map(Number).filter(Number.isFinite),analysis=sr(p);out.push({market,...analysis,tick:p.at(-1)||null,tick_timestamp:msg.history?.times?.at(-1)||null})}}catch(e){const msg=String(e.message||e);if(/limite de taxa|rate limit/i.test(msg)){scanBlockedUntil=Date.now()+5*60_000;runtime.scan_blocked_until=scanBlockedUntil;if(cached.length)return staleScan(cached);throw new Error(`RATE_LIMIT_COOLDOWN: ${msg.slice(0,180)}`)}throw new Error(msg)}latestScan=out.sort((a,b)=>b.score-a.score);lastScanAt=Date.now();runtime.scan_blocked_until=0;return latestScan}
function sr(p){if(p.length<20)return{signal:"WAIT",score:0,regime:"UNKNOWN",zone:null,support_levels:[],resistance_levels:[]};const dif=p.slice(1).map((x,i)=>Math.abs(x-p[i])),atr=dif.slice(-20).reduce((a,b)=>a+b,0)/20,width=atr*Number(mandate.parameters.zone_width_atr),piv=[];for(let i=2;i<p.length-2;i++){const w=p.slice(i-2,i+3);if(p[i]===Math.min(...w))piv.push({i,v:p[i],kind:"SUPPORT"});if(p[i]===Math.max(...w))piv.push({i,v:p[i],kind:"RESISTANCE"})}const zones=piv.map(z=>{const touches=p.filter(x=>Math.abs(x-z.v)<=width).length,rejections=p.slice(1,-1).filter((x,i)=>Math.abs(x-z.v)<=width&&((z.kind==="SUPPORT"&&p[i+2]>x)||(z.kind==="RESISTANCE"&&p[i+2]<x))).length;return{...z,low:z.v-width,high:z.v+width,touches,rejections,quality:Math.min(1,.18+.03*Math.min(touches,8)+.05*Math.min(rejections,6)+.001*Math.min(p.length-z.i,100))}}).sort((a,b)=>b.quality-a.quality);let signal="WAIT",zone=null;for(const z of zones){if(z.quality<mandate.rules.min_quality)continue;const prev=p.at(-2),last=p.at(-1);if(prev>=z.low&&prev<=z.high&&z.kind==="SUPPORT"&&last>prev){signal="CALL";zone=z;break}if(prev>=z.low&&prev<=z.high&&z.kind==="RESISTANCE"&&last<prev){signal="PUT";zone=z;break}}const trend=Math.abs(p.at(-1)-p.at(-20))/(atr*20||1),regime=trend<.35?"RANGING":trend>.8?"TRENDING":"MIXED",fit=regime==="RANGING"?1:regime==="MIXED"?.6:.2,score=.4*fit+.4*(zones[0]?.quality||0)+.2*Math.min(1,atr/(Math.abs(p.at(-1))*.001||1));return{signal,score,regime,zone,support_levels:zones.filter(x=>x.kind==="SUPPORT").slice(0,3),resistance_levels:zones.filter(x=>x.kind==="RESISTANCE").slice(0,3)}}
async function freshDemoSocket(env){
  if(!env.DERIV_TOKEN||!env.DERIV_APP_ID)throw new Error("CREDENTIAL_MISMATCH: missing DERIV_TOKEN or DERIV_APP_ID");
  const h={Authorization:`Bearer ${env.DERIV_TOKEN}`,"Deriv-App-ID":env.DERIV_APP_ID,Accept:"application/json"};
  let a;try{a=await fetch(`${API}/trading/v1/options/accounts`,{headers:h})}catch(e){throw new Error(`PLATFORM_ISSUE: accounts network ${e?.message||"fetch failed"}`)}
  if(!a.ok)throw new Error(`ACCOUNT_API_ERROR: accounts HTTP ${a.status}`)
  const raw=await a.json(),list=Array.isArray(raw.data)?raw.data:(raw.data?.accounts||raw.accounts||[]),demo=list.find(x=>String(x.account_type).toLowerCase()==="demo");
  if(!demo)throw new Error(`CREDENTIAL_MISMATCH: no explicit demo account (accounts=${list.length})`);
  let o;try{o=await fetch(`${API}/trading/v1/options/accounts/${encodeURIComponent(demo.account_id)}/otp`,{method:"POST",headers:h})}catch(e){throw new Error(`PLATFORM_ISSUE: otp network ${e?.message||"fetch failed"}`)}
  if(!o.ok)throw new Error(`OTP_REQUEST_ERROR: otp HTTP ${o.status}`)
  const otp=await o.json(),url=otp?.data?.url;if(!url)throw new Error("CREDENTIAL_MISMATCH: OTP response missing url");
  let u;try{u=new URL(url)}catch(_){throw new Error("CREDENTIAL_MISMATCH: OTP url malformed")}
  if(u.protocol!=="wss:"||u.hostname!=="api.derivws.com"||u.pathname!==DEMO_PATH||!u.searchParams.get("otp"))throw new Error(`CREDENTIAL_MISMATCH: endpoint rejected host=${u.hostname} path=${u.pathname}`);
  return open(url);
}
async function demoSocket(env,runtime){let last;const r=runtime&&Array.isArray(runtime.issues)?runtime:{issues:[]};for(let attempt=1;attempt<=3;attempt++){const started=Date.now();try{return await freshDemoSocket(env)}catch(e){last=e;r.issues.push({at:new Date().toISOString(),code:"WS_RECONNECT_ERROR",attempt,duration_ms:Date.now()-started,message:String(e.message||e).slice(0,240)});if(attempt<3)await new Promise(resolve=>setTimeout(resolve,250*2**(attempt-1)))}}throw new Error(`WS_RECONNECT_ERROR: attempts=3 last=${String(last?.message||last).slice(0,180)}`)}
async function open(url){const safeUrl=(()=>{try{const u=new URL(url);return `${u.protocol}//${u.hostname}${u.pathname}`}catch(_){return "invalid-url"}})();const upgradeUrl=String(url).replace(/^wss:/,"https:");let response;try{response=await fetch(upgradeUrl,{headers:{Upgrade:"websocket"}})}catch(e){throw new Error(`WS_HANDSHAKE_ERROR: network endpoint=${safeUrl} error=${e?.message||"fetch failed"}`)}if(!response.webSocket){if(response.status===401)throw new Error(`OTP_INVALID: websocket HTTP 401 endpoint=${safeUrl}`);if(response.status===408||response.status===504)throw new Error(`WS_TIMEOUT: websocket HTTP ${response.status} endpoint=${safeUrl}`);throw new Error(`WS_HANDSHAKE_ERROR: websocket HTTP ${response.status} endpoint=${safeUrl}`)}const ws=response.webSocket;try{ws.accept()}catch(e){throw new Error(`WS_PROTOCOL_ERROR: websocket accept endpoint=${safeUrl} error=${e?.message||"accept failed"}`)}return ws}
function call(ws,payload,expected){return new Promise((ok,no)=>{const t=setTimeout(()=>done(new Error(`PLATFORM_ISSUE: timeout ${expected}`)),20000),fn=e=>{let m;try{m=JSON.parse(e.data)}catch(_){return}if(m.error)return done(new Error(`PLATFORM_ISSUE: ${m.error.message}`));if(m.req_id===payload.req_id&&(m.msg_type===expected||m[expected]!=null))done(null,m)};function done(e,v){clearTimeout(t);ws.removeEventListener("message",fn);e?no(e):ok(v)}ws.addEventListener("message",fn);ws.send(JSON.stringify(payload))})}
async function publicCall(payload){const ws=await open(PUBLIC);try{return await call(ws,payload,"history")}finally{try{ws.close()}catch(_){}}}
async function sha(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
